version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
