version: "3"
services:
  ethereum:
    container_name: ethereum
    image: ethereum/client-go:stable
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - "ethereum-data:/root"
    command:
      - "--mainnet"
      - "--http"
      - "--http.addr"
      - "0.0.0.0"
      - "--ws"
      - "--ws.addr"
      - "0.0.0.0"
      - "--http.vhosts=*"
volumes:
  ethereum-data: {}
